"""
MAPPS-Lite
Week 5: Electrochemical Candidate Evaluation

This stage takes the raw Materials Project insertion-electrode
matches generated by electrochemical_features.py and converts them
into interpretable scientific screening results.

Inputs:
    data/screened_materials.csv
    data/electrode_matches.csv

Outputs:
    data/electrochemical_evaluation.csv
    reports/electrochemical_evaluation.md

Important:
    A material without a Materials Project insertion-electrode record
    is NOT automatically considered novel.

    It is labeled UNVERIFIED because absence from one database does
    not prove that the material has never been studied as a cathode.
"""

from pathlib import Path
import math
import re

import pandas as pd


# =========================================================
# PROJECT PATHS
# =========================================================

PROJECT_ROOT = Path(__file__).resolve().parent.parent

SCREENED_FILE = (
    PROJECT_ROOT
    / "data"
    / "screened_materials.csv"
)

ELECTRODE_MATCHES_FILE = (
    PROJECT_ROOT
    / "data"
    / "electrode_matches.csv"
)

OUTPUT_FILE = (
    PROJECT_ROOT
    / "data"
    / "electrochemical_evaluation.csv"
)

REPORT_FILE = (
    PROJECT_ROOT
    / "reports"
    / "electrochemical_evaluation.md"
)


# =========================================================
# SETTINGS
# =========================================================

TARGET_STATUS = "PROMISING"

TOP_REPORT_COUNT = 20


# =========================================================
# SCORE WEIGHTS
# =========================================================

WEIGHTS = {
    "voltage": 0.20,
    "capacity": 0.20,
    "energy": 0.20,
    "volume_change": 0.15,
    "stability": 0.20,
    "voltage_steps": 0.05,
}


# =========================================================
# DATA LOADING
# =========================================================

def load_data():
    """
    Load screened MAPPS-Lite candidates and retrieved electrode data.
    """

    if not SCREENED_FILE.exists():
        raise FileNotFoundError(
            f"Missing screened materials file:\n{SCREENED_FILE}"
        )

    if not ELECTRODE_MATCHES_FILE.exists():
        raise FileNotFoundError(
            "Missing electrode matches file:\n"
            f"{ELECTRODE_MATCHES_FILE}\n\n"
            "Run:\n"
            "python src/electrochemical_features.py --limit 0"
        )

    screened = pd.read_csv(
        SCREENED_FILE
    )

    matches = pd.read_csv(
        ELECTRODE_MATCHES_FILE
    )

    required_screened_columns = {
        "material_id",
        "formula",
        "screening_status",
    }

    missing = (
        required_screened_columns
        - set(screened.columns)
    )

    if missing:
        raise ValueError(
            "screened_materials.csv is missing: "
            + ", ".join(sorted(missing))
        )

    return screened, matches


# =========================================================
# NUMERIC HELPERS
# =========================================================

def to_float(value):
    """
    Convert a value to float.

    Returns None for missing or invalid values.
    """

    if value is None:
        return None

    try:
        if pd.isna(value):
            return None

        number = float(value)

        if math.isnan(number):
            return None

        return number

    except (ValueError, TypeError):
        return None


def clamp(value, minimum=0.0, maximum=100.0):
    """
    Restrict a score to the 0-100 range.
    """

    return max(
        minimum,
        min(maximum, value),
    )


def interpolate_score(value, points):
    """
    Piecewise-linear interpolation.

    points should contain tuples:

        (physical_value, score)

    Example:

        [
            (2.0, 0),
            (3.0, 60),
            (3.5, 100),
        ]
    """

    if value is None:
        return None

    points = sorted(
        points,
        key=lambda item: item[0],
    )

    if value <= points[0][0]:
        return float(points[0][1])

    if value >= points[-1][0]:
        return float(points[-1][1])

    for index in range(
        len(points) - 1
    ):
        x1, y1 = points[index]
        x2, y2 = points[index + 1]

        if x1 <= value <= x2:
            fraction = (
                (value - x1)
                / (x2 - x1)
            )

            score = (
                y1
                + fraction
                * (y2 - y1)
            )

            return float(score)

    return None


# =========================================================
# SCIENTIFIC SUB-SCORES
# =========================================================

def calculate_voltage_score(voltage):
    """
    Evaluate average cathode voltage.

    The scoring favors roughly 3.5-4.3 V.

    Very low voltages reduce energy density.

    Extremely high voltages are not automatically rewarded because
    high-voltage operation can create electrolyte and structural
    stability challenges.
    """

    return interpolate_score(
        voltage,
        [
            (1.5, 0),
            (2.0, 15),
            (2.5, 35),
            (3.0, 65),
            (3.5, 100),
            (4.0, 100),
            (4.3, 100),
            (4.5, 85),
            (5.0, 45),
            (5.5, 10),
            (6.0, 0),
        ],
    )


def calculate_capacity_score(capacity):
    """
    Evaluate gravimetric capacity in mAh/g.

    Larger capacity generally increases stored charge per unit mass.
    """

    return interpolate_score(
        capacity,
        [
            (0, 0),
            (50, 10),
            (100, 50),
            (150, 75),
            (200, 100),
            (300, 100),
        ],
    )


def calculate_energy_score(energy):
    """
    Evaluate gravimetric specific energy in Wh/kg.
    """

    return interpolate_score(
        energy,
        [
            (0, 0),
            (150, 10),
            (300, 40),
            (500, 75),
            (700, 100),
            (1000, 100),
        ],
    )


def calculate_volume_score(volume_change):
    """
    Evaluate structural volume change during cycling.

    Smaller structural changes are preferred because large expansion
    or contraction may contribute to mechanical degradation.
    """

    if volume_change is None:
        return None

    volume_change = abs(
        volume_change
    )

    return interpolate_score(
        volume_change,
        [
            (0, 100),
            (5, 100),
            (10, 85),
            (15, 65),
            (25, 35),
            (40, 0),
            (100, 0),
        ],
    )


def calculate_stability_score(
    stability_charge,
    stability_discharge,
):
    """
    Evaluate thermodynamic stability.

    Materials Project stability values correspond to energy above
    hull for the charged and discharged endpoint materials.

    The less-stable endpoint is used so that a highly unstable
    charged or discharged phase cannot be hidden by a stable
    opposite endpoint.
    """

    available = []

    if stability_charge is not None:
        available.append(
            stability_charge
        )

    if stability_discharge is not None:
        available.append(
            stability_discharge
        )

    if not available:
        return None

    worst_stability = max(
        available
    )

    return interpolate_score(
        worst_stability,
        [
            (0.00, 100),
            (0.025, 100),
            (0.05, 85),
            (0.10, 55),
            (0.20, 20),
            (0.30, 0),
            (1.00, 0),
        ],
    )


def calculate_voltage_step_score(
    num_steps,
):
    """
    Score the complexity of the voltage profile.

    Fewer distinct stable intermediate steps receive a modest
    preference.

    This has intentionally low weight because multi-step behavior
    is not inherently disqualifying.
    """

    if num_steps is None:
        return None

    return interpolate_score(
        num_steps,
        [
            (1, 100),
            (2, 90),
            (3, 75),
            (4, 60),
            (5, 50),
            (8, 30),
            (12, 20),
        ],
    )


# =========================================================
# MATERIAL-ID MATCHING
# =========================================================

def extract_material_ids(value):
    """
    Extract Materials Project IDs such as mp-12345 from an electrode
    material_ids field.
    """

    if value is None:
        return set()

    try:
        if pd.isna(value):
            return set()
    except TypeError:
        pass

    text = str(value)

    ids = re.findall(
        r"mp-\d+",
        text,
    )

    return set(ids)


def determine_match_type(
    candidate_material_id,
    electrode_material_ids,
):
    """
    Determine whether the exact candidate structure participates in
    the Materials Project electrode pathway.

    DIRECT_STRUCTURE_MATCH:
        The candidate's exact mp-ID appears in the electrode path.

    FORMULA_FAMILY_MATCH:
        Materials Project contains an electrode system associated
        with the formula, but this exact mp-ID is not present.
    """

    material_ids = extract_material_ids(
        electrode_material_ids
    )

    if candidate_material_id in material_ids:
        return "DIRECT_STRUCTURE_MATCH"

    return "FORMULA_FAMILY_MATCH"


# =========================================================
# LITHIUM CHANGE
# =========================================================

def calculate_lithium_fraction_change(
    fraction_charge,
    fraction_discharge,
):
    """
    Calculate the change in lithium atomic fraction between charged
    and discharged endpoint compositions.
    """

    if (
        fraction_charge is None
        or fraction_discharge is None
    ):
        return None

    return (
        fraction_discharge
        - fraction_charge
    )


# =========================================================
# ELECTROCHEMICAL SCORE
# =========================================================

def evaluate_electrode_record(
    candidate_material_id,
    record,
):
    """
    Score one Materials Project electrode record.

    The final score is a weighted screening score.

    It is NOT a prediction of real experimental cycle life,
    rate capability, safety, or commercial viability.
    """

    voltage = to_float(
        record.get(
            "average_voltage_V"
        )
    )

    capacity = to_float(
        record.get(
            "capacity_grav_mAh_g"
        )
    )

    energy = to_float(
        record.get(
            "energy_grav_Wh_kg"
        )
    )

    volume_change = to_float(
        record.get(
            "max_volume_change_percent"
        )
    )

    stability_charge = to_float(
        record.get(
            "stability_charge_eV_atom"
        )
    )

    stability_discharge = to_float(
        record.get(
            "stability_discharge_eV_atom"
        )
    )

    num_steps = to_float(
        record.get(
            "num_voltage_steps"
        )
    )

    fraction_charge = to_float(
        record.get(
            "li_fraction_charge"
        )
    )

    fraction_discharge = to_float(
        record.get(
            "li_fraction_discharge"
        )
    )

    scores = {
        "voltage":
            calculate_voltage_score(
                voltage
            ),

        "capacity":
            calculate_capacity_score(
                capacity
            ),

        "energy":
            calculate_energy_score(
                energy
            ),

        "volume_change":
            calculate_volume_score(
                volume_change
            ),

        "stability":
            calculate_stability_score(
                stability_charge,
                stability_discharge,
            ),

        "voltage_steps":
            calculate_voltage_step_score(
                num_steps
            ),
    }

    weighted_total = 0.0
    available_weight = 0.0
    available_metrics = 0

    for metric, score in scores.items():

        if score is None:
            continue

        weight = WEIGHTS[metric]

        weighted_total += (
            score * weight
        )

        available_weight += weight
        available_metrics += 1

    if available_weight == 0:
        raw_score = None
        completeness = 0.0
        adjusted_score = None

    else:
        raw_score = (
            weighted_total
            / available_weight
        )

        completeness = (
            available_metrics
            / len(WEIGHTS)
        )

        # ---------------------------------------------
        # Reduce confidence when only a small portion
        # of the desired electrochemical data exists.
        # ---------------------------------------------

        confidence_factor = (
            0.50
            + 0.50 * completeness
        )

        adjusted_score = (
            raw_score
            * confidence_factor
        )

    match_type = determine_match_type(
        candidate_material_id,
        record.get(
            "electrode_material_ids"
        ),
    )

    lithium_fraction_change = (
        calculate_lithium_fraction_change(
            fraction_charge,
            fraction_discharge,
        )
    )

    return {
        "database_match_type":
            match_type,

        "electrochemical_score_raw":
            raw_score,

        "electrochemical_score":
            adjusted_score,

        "electrochemical_data_completeness":
            completeness,

        "voltage_score":
            scores["voltage"],

        "capacity_score":
            scores["capacity"],

        "energy_score":
            scores["energy"],

        "volume_change_score":
            scores["volume_change"],

        "stability_score":
            scores["stability"],

        "voltage_steps_score":
            scores["voltage_steps"],

        "li_fraction_change":
            lithium_fraction_change,
    }


# =========================================================
# RATING
# =========================================================

def determine_electrochemical_rating(
    score,
):
    """
    Convert the electrochemical score into an interpretable category.
    """

    if score is None:
        return "UNVERIFIED"

    if score >= 80:
        return "HIGH_PRIORITY"

    if score >= 65:
        return "PROMISING"

    if score >= 50:
        return "MODERATE"

    return "LOW_PRIORITY"


# =========================================================
# SELECT BEST ELECTRODE RECORD
# =========================================================

def select_best_record(
    candidate_material_id,
    candidate_matches,
):
    """
    Evaluate every matching electrode record and select the strongest
    scientifically relevant record.

    Direct structural matches are preferred over formula-only matches.

    If multiple direct matches exist, the highest-scoring one is used.
    """

    evaluated_records = []

    for _, record in (
        candidate_matches.iterrows()
    ):

        evaluation = (
            evaluate_electrode_record(
                candidate_material_id,
                record,
            )
        )

        combined = record.to_dict()

        combined.update(
            evaluation
        )

        evaluated_records.append(
            combined
        )

    if not evaluated_records:
        return None

    direct_records = [
        record
        for record in evaluated_records
        if record[
            "database_match_type"
        ] == "DIRECT_STRUCTURE_MATCH"
    ]

    if direct_records:
        pool = direct_records
    else:
        pool = evaluated_records

    def ranking_score(record):
        score = record.get(
            "electrochemical_score"
        )

        if score is None:
            return -1

        return score

    return max(
        pool,
        key=ranking_score,
    )


# =========================================================
# BUILD COMPLETE CANDIDATE EVALUATION
# =========================================================

def evaluate_candidates(
    screened,
    matches,
):
    """
    Evaluate all PROMISING MAPPS-Lite candidates.

    Candidates without electrode database matches remain in the
    output and are labeled NO_MP_ELECTRODE_RECORD / UNVERIFIED.
    """

    candidates = screened[
        screened["screening_status"]
        .astype(str)
        .str.upper()
        == TARGET_STATUS
    ].copy()

    if "rank" in candidates.columns:
        candidates = candidates.sort_values(
            "rank"
        )

    print()
    print("=" * 72)
    print("MAPPS-Lite Week 5")
    print("Electrochemical Candidate Evaluation")
    print("=" * 72)

    print(
        f"{TARGET_STATUS} candidates: "
        f"{len(candidates):,}"
    )

    print(
        "Electrode records available: "
        f"{len(matches):,}"
    )

    print()

    results = []

    for position, (_, candidate) in enumerate(
        candidates.iterrows(),
        start=1,
    ):
        candidate_id = candidate[
            "material_id"
        ]

        formula = candidate[
            "formula"
        ]

        print(
            f"[{position}/{len(candidates)}] "
            f"{candidate_id} | {formula}"
        )

        if matches.empty:
            candidate_matches = (
                pd.DataFrame()
            )

        else:
            candidate_matches = matches[
                matches[
                    "candidate_material_id"
                ].astype(str)
                == str(candidate_id)
            ].copy()

        base_result = {
            "material_id":
                candidate_id,

            "formula":
                formula,

            "original_rank":
                candidate.get("rank"),

            "original_overall_score":
                candidate.get(
                    "overall_score"
                ),

            "original_screening_status":
                candidate.get(
                    "screening_status"
                ),

            "mp_electrode_record_count":
                len(candidate_matches),
        }

        # -------------------------------------------------
        # NO ELECTRODE RECORD
        # -------------------------------------------------

        if candidate_matches.empty:

            print(
                "  No MP electrode record "
                "-> UNVERIFIED"
            )

            base_result.update(
                {
                    "database_match_type":
                        "NO_MP_ELECTRODE_RECORD",

                    "electrochemical_rating":
                        "UNVERIFIED",

                    "electrochemical_score":
                        None,

                    "electrochemical_score_raw":
                        None,

                    "electrochemical_data_completeness":
                        0.0,
                }
            )

            results.append(
                base_result
            )

            continue

        # -------------------------------------------------
        # ELECTRODE RECORD EXISTS
        # -------------------------------------------------

        best = select_best_record(
            candidate_id,
            candidate_matches,
        )

        score = best.get(
            "electrochemical_score"
        )

        rating = (
            determine_electrochemical_rating(
                score
            )
        )

        print(
            f"  {best['database_match_type']} "
            f"| score={score:.1f} "
            f"| {rating}"
            if score is not None
            else
            f"  {best['database_match_type']} "
            "| insufficient numerical data"
        )

        base_result.update(
            {
                "database_match_type":
                    best.get(
                        "database_match_type"
                    ),

                "electrochemical_rating":
                    rating,

                "electrochemical_score":
                    best.get(
                        "electrochemical_score"
                    ),

                "electrochemical_score_raw":
                    best.get(
                        "electrochemical_score_raw"
                    ),

                "electrochemical_data_completeness":
                    best.get(
                        "electrochemical_data_completeness"
                    ),

                "battery_type":
                    best.get(
                        "battery_type"
                    ),

                "battery_formula":
                    best.get(
                        "battery_formula"
                    ),

                "electrode_material_ids":
                    best.get(
                        "electrode_material_ids"
                    ),

                "framework":
                    best.get(
                        "framework"
                    ),

                "framework_formula":
                    best.get(
                        "framework_formula"
                    ),

                "formula_charge":
                    best.get(
                        "formula_charge"
                    ),

                "formula_discharge":
                    best.get(
                        "formula_discharge"
                    ),

                "charged_material_id":
                    best.get(
                        "charged_material_id"
                    ),

                "discharged_material_id":
                    best.get(
                        "discharged_material_id"
                    ),

                "average_voltage_V":
                    best.get(
                        "average_voltage_V"
                    ),

                "capacity_grav_mAh_g":
                    best.get(
                        "capacity_grav_mAh_g"
                    ),

                "capacity_vol_mAh_cc":
                    best.get(
                        "capacity_vol_mAh_cc"
                    ),

                "energy_grav_Wh_kg":
                    best.get(
                        "energy_grav_Wh_kg"
                    ),

                "energy_vol_Wh_L":
                    best.get(
                        "energy_vol_Wh_L"
                    ),

                "li_fraction_charge":
                    best.get(
                        "li_fraction_charge"
                    ),

                "li_fraction_discharge":
                    best.get(
                        "li_fraction_discharge"
                    ),

                "li_fraction_change":
                    best.get(
                        "li_fraction_change"
                    ),

                "num_voltage_steps":
                    best.get(
                        "num_voltage_steps"
                    ),

                "max_voltage_step_V":
                    best.get(
                        "max_voltage_step_V"
                    ),

                "max_volume_change_percent":
                    best.get(
                        "max_volume_change_percent"
                    ),

                "stability_charge_eV_atom":
                    best.get(
                        "stability_charge_eV_atom"
                    ),

                "stability_discharge_eV_atom":
                    best.get(
                        "stability_discharge_eV_atom"
                    ),

                "voltage_score":
                    best.get(
                        "voltage_score"
                    ),

                "capacity_score":
                    best.get(
                        "capacity_score"
                    ),

                "energy_score":
                    best.get(
                        "energy_score"
                    ),

                "volume_change_score":
                    best.get(
                        "volume_change_score"
                    ),

                "stability_score":
                    best.get(
                        "stability_score"
                    ),

                "voltage_steps_score":
                    best.get(
                        "voltage_steps_score"
                    ),
            }
        )

        results.append(
            base_result
        )

    evaluation = pd.DataFrame(
        results
    )

    return evaluation


# =========================================================
# SORT RESULTS
# =========================================================

def sort_evaluation(evaluation):
    """
    Sort verified candidates by electrochemical score while preserving
    unverified candidates at the bottom.
    """

    evidence_order = {
        "DIRECT_STRUCTURE_MATCH": 0,
        "FORMULA_FAMILY_MATCH": 1,
        "NO_MP_ELECTRODE_RECORD": 2,
    }

    evaluation[
        "_evidence_order"
    ] = (
        evaluation[
            "database_match_type"
        ]
        .map(evidence_order)
        .fillna(3)
    )

    evaluation = evaluation.sort_values(
        by=[
            "_evidence_order",
            "electrochemical_score",
            "original_rank",
        ],
        ascending=[
            True,
            False,
            True,
        ],
        na_position="last",
    )

    evaluation = evaluation.drop(
        columns=[
            "_evidence_order"
        ]
    )

    evaluation.insert(
        0,
        "week5_electrochemical_rank",
        range(
            1,
            len(evaluation) + 1,
        ),
    )

    return evaluation


# =========================================================
# SAVE CSV
# =========================================================

def save_evaluation(evaluation):
    """
    Save Week 5 candidate evaluation.
    """

    OUTPUT_FILE.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    evaluation.to_csv(
        OUTPUT_FILE,
        index=False,
    )

    print()
    print(
        "Electrochemical evaluation saved to:"
    )

    print(
        OUTPUT_FILE
    )


# =========================================================
# MARKDOWN TABLE
# =========================================================

def format_value(value, decimals=2):
    """
    Format values for the Markdown report.
    """

    if value is None:
        return "-"

    try:
        if pd.isna(value):
            return "-"
    except TypeError:
        pass

    if isinstance(
        value,
        (float, int),
    ):
        return f"{value:.{decimals}f}"

    return str(value)


def create_markdown_table(rows):
    """
    Build a small Markdown table without requiring the optional
    'tabulate' Python dependency.
    """

    header = (
        "| Rank | Material | Formula | Evidence | "
        "Score | Voltage (V) | Capacity (mAh/g) | "
        "Energy (Wh/kg) | Volume Δ (%) | Rating |\n"
    )

    separator = (
        "|---:|---|---|---|---:|---:|---:|---:|---:|---|\n"
    )

    lines = [
        header,
        separator,
    ]

    for _, row in rows.iterrows():

        line = (
            f"| {row.get('week5_electrochemical_rank', '-')} "
            f"| {row.get('material_id', '-')} "
            f"| {row.get('formula', '-')} "
            f"| {row.get('database_match_type', '-')} "
            f"| {format_value(row.get('electrochemical_score'), 1)} "
            f"| {format_value(row.get('average_voltage_V'))} "
            f"| {format_value(row.get('capacity_grav_mAh_g'), 1)} "
            f"| {format_value(row.get('energy_grav_Wh_kg'), 1)} "
            f"| {format_value(row.get('max_volume_change_percent'), 1)} "
            f"| {row.get('electrochemical_rating', '-')} |\n"
        )

        lines.append(
            line
        )

    return "".join(lines)


# =========================================================
# GENERATE REPORT
# =========================================================

def generate_report(evaluation):
    """
    Generate an interpretable Week 5 electrochemical report.
    """

    REPORT_FILE.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    total = len(
        evaluation
    )

    direct = (
        evaluation[
            "database_match_type"
        ]
        == "DIRECT_STRUCTURE_MATCH"
    ).sum()

    family = (
        evaluation[
            "database_match_type"
        ]
        == "FORMULA_FAMILY_MATCH"
    ).sum()

    unverified = (
        evaluation[
            "database_match_type"
        ]
        == "NO_MP_ELECTRODE_RECORD"
    ).sum()

    high_priority = (
        evaluation[
            "electrochemical_rating"
        ]
        == "HIGH_PRIORITY"
    ).sum()

    promising = (
        evaluation[
            "electrochemical_rating"
        ]
        == "PROMISING"
    ).sum()

    moderate = (
        evaluation[
            "electrochemical_rating"
        ]
        == "MODERATE"
    ).sum()

    low_priority = (
        evaluation[
            "electrochemical_rating"
        ]
        == "LOW_PRIORITY"
    ).sum()

    verified = evaluation[
        evaluation[
            "electrochemical_score"
        ].notna()
    ].copy()

    top = verified.head(
        TOP_REPORT_COUNT
    )

    report = []

    report.append(
        "# MAPPS-Lite Week 5 Electrochemical Evaluation\n\n"
    )

    report.append(
        "## Purpose\n\n"
    )

    report.append(
        "This report evaluates MAPPS-Lite PROMISING cathode "
        "candidates using lithium insertion-electrode properties "
        "retrieved from Materials Project.\n\n"
    )

    report.append(
        "The electrochemical score is a screening metric rather "
        "than a prediction of experimental battery performance. "
        "Cycle life, rate capability, electronic conductivity, "
        "ionic diffusivity, synthesis feasibility, electrolyte "
        "compatibility, and safety still require additional "
        "evaluation.\n\n"
    )

    report.append(
        "## Database Evidence\n\n"
    )

    report.append(
        f"- PROMISING candidates evaluated: **{total}**\n"
    )

    report.append(
        f"- Exact MP structure matches: **{direct}**\n"
    )

    report.append(
        f"- Formula-family electrode matches: **{family}**\n"
    )

    report.append(
        f"- No MP insertion-electrode record: **{unverified}**\n\n"
    )

    report.append(
        "A candidate with no Materials Project electrode record "
        "is labeled **UNVERIFIED**, not novel. Database absence "
        "alone is not evidence that a material has never been "
        "studied experimentally or computationally.\n\n"
    )

    report.append(
        "## Electrochemical Ratings\n\n"
    )

    report.append(
        f"- HIGH_PRIORITY: **{high_priority}**\n"
    )

    report.append(
        f"- PROMISING: **{promising}**\n"
    )

    report.append(
        f"- MODERATE: **{moderate}**\n"
    )

    report.append(
        f"- LOW_PRIORITY: **{low_priority}**\n"
    )

    report.append(
        f"- UNVERIFIED: **{unverified}**\n\n"
    )

    report.append(
        "## Scoring Method\n\n"
    )

    report.append(
        "The screening score combines:\n\n"
    )

    report.append(
        "- average voltage: 20%\n"
        "- gravimetric capacity: 20%\n"
        "- gravimetric specific energy: 20%\n"
        "- maximum volume change: 15%\n"
        "- charged/discharged thermodynamic stability: 20%\n"
        "- voltage-step complexity: 5%\n\n"
    )

    report.append(
        "Missing electrochemical fields reduce the confidence-adjusted "
        "score rather than being silently treated as ideal values.\n\n"
    )

    report.append(
        "## Match Definitions\n\n"
    )

    report.append(
        "**DIRECT_STRUCTURE_MATCH** means the candidate's exact "
        "Materials Project material ID occurs in the retrieved "
        "lithium insertion pathway.\n\n"
    )

    report.append(
        "**FORMULA_FAMILY_MATCH** means an electrode pathway was "
        "found for the same chemical formula, but the exact candidate "
        "structure ID was not identified in that pathway.\n\n"
    )

    report.append(
        "**NO_MP_ELECTRODE_RECORD** means no insertion-electrode "
        "entry was returned for that candidate formula.\n\n"
    )

    report.append(
        "## Highest-Ranked Verified Candidates\n\n"
    )

    if top.empty:
        report.append(
            "No candidates currently have usable Materials Project "
            "electrochemical data.\n"
        )

    else:
        report.append(
            create_markdown_table(
                top
            )
        )

    with open(
        REPORT_FILE,
        "w",
        encoding="utf-8",
    ) as file:
        file.write(
            "".join(report)
        )

    print(
        "Electrochemical report saved to:"
    )

    print(
        REPORT_FILE
    )


# =========================================================
# TERMINAL SUMMARY
# =========================================================

def print_summary(evaluation):
    """
    Print Week 5 evaluation statistics and top candidates.
    """

    direct = (
        evaluation[
            "database_match_type"
        ]
        == "DIRECT_STRUCTURE_MATCH"
    ).sum()

    family = (
        evaluation[
            "database_match_type"
        ]
        == "FORMULA_FAMILY_MATCH"
    ).sum()

    unverified = (
        evaluation[
            "database_match_type"
        ]
        == "NO_MP_ELECTRODE_RECORD"
    ).sum()

    print()
    print("=" * 72)
    print("WEEK 5 ELECTROCHEMICAL SUMMARY")
    print("=" * 72)

    print(
        f"Direct structure matches: {direct}"
    )

    print(
        f"Formula-family matches:   {family}"
    )

    print(
        f"Unverified candidates:    {unverified}"
    )

    print()

    rating_counts = (
        evaluation[
            "electrochemical_rating"
        ]
        .value_counts()
    )

    print(
        "Ratings:"
    )

    for rating, count in (
        rating_counts.items()
    ):
        print(
            f"  {rating:<15} {count}"
        )

    verified = evaluation[
        evaluation[
            "electrochemical_score"
        ].notna()
    ].head(10)

    print()
    print(
        "Top verified candidates:"
    )

    if verified.empty:
        print(
            "  No verified electrode candidates found."
        )

    else:
        for _, row in (
            verified.iterrows()
        ):

            score = row[
                "electrochemical_score"
            ]

            print(
                f"  {row['material_id']:<12} "
                f"{row['formula']:<22} "
                f"{score:6.1f}  "
                f"{row['database_match_type']}"
            )

    print("=" * 72)


# =========================================================
# MAIN
# =========================================================

def main():
    """
    Run Week 5 electrochemical candidate evaluation.
    """

    print(
        "Loading Week 5 data..."
    )

    screened, matches = (
        load_data()
    )

    evaluation = (
        evaluate_candidates(
            screened,
            matches,
        )
    )

    evaluation = (
        sort_evaluation(
            evaluation
        )
    )

    save_evaluation(
        evaluation
    )

    generate_report(
        evaluation
    )

    print_summary(
        evaluation
    )

    print()
    print(
        "Week 5 electrochemical evaluation "
        "completed successfully."
    )


if __name__ == "__main__":
    main()